INSERT INTO product_categories (strapi_id, name, slug, description, sort_order, is_active, updated_at)
VALUES (NULL, 'Flower Vending Machines', 'flower-vending-machines', 'Temperature-controlled vending systems designed for bouquets and fresh flower retail.', 40, 1, '2026-05-29T06:35:12.506Z')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  description=excluded.description,
  is_active=1,
  updated_at=excluded.updated_at;
INSERT INTO product_categories (strapi_id, name, slug, description, sort_order, is_active, updated_at)
VALUES (NULL, 'Pet Vending Stations', 'pet-vending-stations', 'Automated vending and service stations for pet food, treats, washing, and pet care products.', 41, 1, '2026-05-29T06:35:12.506Z')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  description=excluded.description,
  is_active=1,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Outdoor Self Service Dog Wash Machine for Parks, Communities & Gas Stations',
  'outdoor-self-service-dog-wash-machine-for-parks-communities-gas-stations',
  'Outdoor Self-service Dog Wash Machine',
  'Commercial outdoor self service dog wash machine designed with a weatherproof stainless steel structure. Ideal for parks, communities, and gas stations, featuring waterproof touch screen, automatic disinfection, adjustable hot water, and multi-liquid system for unattended operation.',
  'Commercial outdoor self service dog wash machine designed with a weatherproof stainless steel structure. Ideal for parks, communities, and gas stations, featuring waterproof touch screen, automatic disinfection, adjustable hot water, and multi-liquid system for unattended operation.',
  NULL,
  '1 unit',
  '800 unit / Month',
  'China',
  '45 Days',
  'Micron Vending',
  'https://www.micronvending.com/outdoor-self-service-dog-wash-machine-designed-for-outdoor-placement-with-weatherproof-structure.html',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/FceacBBGzy.png?imageMogr2/format/webp/auto-orient',
  '["https://yunpan.cdn.site.joinf.com/5009640932269608/FceacBBGzy.png?imageMogr2/format/webp/auto-orient","https://yunpan.cdn.site.joinf.com/5009640932269608/CbfWjiE2X7.png?imageMogr2/format/webp/auto-orient"]',
  NULL,
  '["Commercial outdoor self service dog wash machine designed with a weatherproof stainless steel structure"]',
  '[["Model NO.","Outdoor Self-service Dog Wash Machine"],["Minimum order quantity","1 unit"],["Supply Ability","800 unit / Month"],["Country of Origin","China"],["Stock Time","45 Days"]]',
  0,
  1000,
  'Outdoor Self Service Dog Wash Machine for Parks, Communities & Gas Stations',
  'Commercial outdoor self service dog wash machine designed with a weatherproof stainless steel structure. Ideal for parks, communities, and gas stations, featuring waterproof touch screen, automatic disinfection, adjustable hot water, and multi-liquid system for unattended operation.',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/FceacBBGzy.png?imageMogr2/format/webp/auto-orient',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Self Service Dog Wash Machine with Advertising Screen | Commercial Pet Washing Station',
  'self-service-dog-wash-machine-with-advertising-screen-commercial-pet-washing-station',
  'Dog Wash Machine',
  'Commercial self service dog wash machine designed for pet shops, malls, and grooming businesses. Features touch screen operation, advertising display, stainless steel body, multiple liquid tanks, adjustable hot water, and smart backend system. Ideal for generating stable pet service revenue.',
  'Commercial self service dog wash machine designed for pet shops, malls, and grooming businesses. Features touch screen operation, advertising display, stainless steel body, multiple liquid tanks, adjustable hot water, and smart backend system. Ideal for generating stable pet service revenue.',
  NULL,
  '1 unit',
  '800 unit / Month',
  'China',
  '60 Days',
  'Micron Vending',
  'https://www.micronvending.com/self-service-dog-wash-machine-for-pet-businesses-with-304-stainless-steel.html',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/XSadWXbhES.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '[]',
  'https://vod.site.joinf.com/5009640932269608/4X4aEn6XCK.mp4',
  '["Commercial self service dog wash machine designed for pet shops, malls, and grooming businesses","Features touch screen operation, advertising display, stainless steel body, multiple liquid tanks, adjustable hot water, and smart backend system"]',
  '[["Model NO.","Dog Wash Machine"],["Minimum order quantity","1 unit"],["Supply Ability","800 unit / Month"],["Country of Origin","China"],["Stock Time","60 Days"]]',
  0,
  1001,
  'Self Service Dog Wash Machine with Advertising Screen | Commercial Pet Washing Station',
  'Commercial self service dog wash machine designed for pet shops, malls, and grooming businesses. Features touch screen operation, advertising display, stainless steel body, multiple liquid tanks, adjustable hot water, and smart backend system. Ideal for generating stable pet service revenue.',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/XSadWXbhES.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Pet Grooming Supplies Locker Vending Machine for Shampoo, Towels & Care Products',
  'pet-grooming-supplies-locker-vending-machine-for-shampoo-towels-care-products',
  'Pet grooming product vending machine',
  'Pet grooming supplies locker vending machine designed for pet grooming shops. Ideal for selling pet shampoo, conditioner, towels, and bathing accessories with flexible lockers and smart management.',
  'Pet grooming supplies locker vending machine designed for pet grooming shops. Ideal for selling pet shampoo, conditioner, towels, and bathing accessories with flexible lockers and smart management.',
  NULL,
  '1 unit',
  '1500 unit / Month',
  'China',
  '45 Days',
  'Micron Vending',
  'https://www.micronvending.com/Pet-Grooming-Supplies-Locker-Vending-Machine.html',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/eYEP7MNfkN.jpg?imageMogr2/format/webp/auto-orient',
  '["https://yunpan.cdn.site.joinf.com/5009640932269608/eYEP7MNfkN.jpg?imageMogr2/format/webp/auto-orient"]',
  NULL,
  '["Pet grooming supplies locker vending machine designed for pet grooming shops","Ideal for selling pet shampoo, conditioner, towels, and bathing accessories with flexible lockers and smart management"]',
  '[["Model NO.","Pet grooming product vending machine"],["Minimum order quantity","1 unit"],["Supply Ability","1500 unit / Month"],["Country of Origin","China"],["Stock Time","45 Days"]]',
  0,
  1002,
  'Pet Grooming Supplies Locker Vending Machine for Shampoo, Towels & Care Products',
  'Pet grooming supplies locker vending machine designed for pet grooming shops. Ideal for selling pet shampoo, conditioner, towels, and bathing accessories with flexible lockers and smart management.',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/eYEP7MNfkN.jpg?imageMogr2/format/webp/auto-orient',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Self Service Dog Wash Machine | Outdoor Pet Washing Vending Machine Solution',
  'self-service-dog-wash-machine-outdoor-pet-washing-vending-machine-solution',
  'Self-Service Dog Wash Machine',
  'Discover our self service dog wash machine designed for parks, pet stores, and commercial use. A smart, automated solution for convenient pet washing with low maintenance and high efficiency.',
  'Discover our self service dog wash machine designed for parks, pet stores, and commercial use. A smart, automated solution for convenient pet washing with low maintenance and high efficiency.',
  'DDP,DDU,CIF,FOB,EXW',
  '1 unit',
  '800 unit / Month',
  'China',
  '60 Days',
  'Micron Vending',
  'https://www.micronvending.com/Self-Service-Dog-Wash-Machine-for-Outdoor-Commercial-Pet-Care-Solutions.html',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/7H2jWjFez6.png?imageMogr2/format/webp/auto-orient',
  '["https://yunpan.cdn.site.joinf.com/5009640932269608/7H2jWjFez6.png?imageMogr2/format/webp/auto-orient"]',
  NULL,
  '["Discover our self service dog wash machine designed for parks, pet stores, and commercial use"]',
  '[["Model NO.","Self-Service Dog Wash Machine"],["Delivery","DDP,DDU,CIF,FOB,EXW"],["Minimum order quantity","1 unit"],["Supply Ability","800 unit / Month"],["Country of Origin","China"],["Stock Time","60 Days"]]',
  0,
  1003,
  'Self Service Dog Wash Machine | Outdoor Pet Washing Vending Machine Solution',
  'Discover our self service dog wash machine designed for parks, pet stores, and commercial use. A smart, automated solution for convenient pet washing with low maintenance and high efficiency.',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/7H2jWjFez6.png?imageMogr2/format/webp/auto-orient',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Hygienic & Convenient Self-Service Dog Wash Machine',
  'hygienic-convenient-self-service-dog-wash-machine',
  'self serve dog washing machine',
  'Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation.',
  'Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation.',
  'FOB',
  '1 set',
  '800 set / Month',
  'China',
  '45 Days',
  'Micron Vending',
  'https://www.micronvending.com/product-Affordable-Self-Service-Dog-Wash-Machine-Hygienic-Convenient-Smart-Solutions-Pet-Washing-Businesses.html',
  'https://yunpan.cdn.site.joinf.com/5218418803719614/HE7w2QaciG.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '[]',
  NULL,
  '["Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation","Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation","Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation"]',
  '[["Model NO.","self serve dog washing machine"],["Delivery","FOB"],["Minimum order quantity","1 set"],["Supply Ability","800 set / Month"],["Country of Origin","China"],["Stock Time","45 Days"]]',
  0,
  1004,
  'Hygienic & Convenient Self-Service Dog Wash Machine',
  'Smart self-service pet washing vending machine with touch screen, card and coin payment, and SDK integration for easy, hygienic, and profitable operation.',
  'https://yunpan.cdn.site.joinf.com/5218418803719614/HE7w2QaciG.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Commercial Self-Service Dog Wash Machine for Pet Shops & Communities',
  'commercial-self-service-dog-wash-machine-for-pet-shops-communities',
  'Dog Wash Station',
  'Commercial self-service dog wash machine designed for pet shops, grooming salons, and residential communities. Reduce labor costs and create new revenue with automated wash programs.',
  'Commercial self-service dog wash machine designed for pet shops, grooming salons, and residential communities. Reduce labor costs and create new revenue with automated wash programs.',
  'DDP, CIF, FOB, EXW',
  '1 unit',
  '800 unit / Month',
  'China',
  '45 Days',
  'Micron Vending',
  'https://www.micronvending.com/Self-Service-Dog-Wash-Machine-for-Pet-Shops-Grooming-Salons-Residential-Communities.html',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/t42kySARhT.png?imageMogr2/format/webp/auto-orient',
  '["https://yunpan.cdn.site.joinf.com/5009640932269608/t42kySARhT.png?imageMogr2/format/webp/auto-orient"]',
  NULL,
  '["Commercial self-service dog wash machine designed for pet shops, grooming salons, and residential communities"]',
  '[["Model NO.","Dog Wash Station"],["Delivery","DDP, CIF, FOB, EXW"],["Minimum order quantity","1 unit"],["Supply Ability","800 unit / Month"],["Country of Origin","China"],["Stock Time","45 Days"]]',
  0,
  1005,
  'Commercial Self-Service Dog Wash Machine for Pet Shops & Communities',
  'Commercial self-service dog wash machine designed for pet shops, grooming salons, and residential communities. Reduce labor costs and create new revenue with automated wash programs.',
  'https://yunpan.cdn.site.joinf.com/5009640932269608/t42kySARhT.png?imageMogr2/format/webp/auto-orient',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
INSERT INTO products (
  strapi_id, category_id, category_slug, name, slug, model_number, short_description, overview,
  delivery, minimum_order_quantity, supply_ability, country_of_origin, stock_time, source_site, source_url,
  cover_image_url, gallery_json, video_url, key_features_json, specifications_json, is_featured, sort_order,
  seo_title, seo_description, og_image_url, published_at, updated_at
) VALUES (
  NULL,
  (SELECT id FROM product_categories WHERE slug = 'pet-vending-stations' LIMIT 1),
  'pet-vending-stations',
  'Affordable Self-Service Dog Wash Stations for Pet Washing Businesses',
  'affordable-self-service-dog-wash-stations-for-pet-washing-businesses',
  'self dog washing machine',
  'Boost your business with our self-service dog washing station. Featuring a smart backend, flexible payments, and advanced hygiene features. Perfect for parks, gas stations, and pet-friendly locations.',
  'Boost your business with our self-service dog washing station. Featuring a smart backend, flexible payments, and advanced hygiene features. Perfect for parks, gas stations, and pet-friendly locations.',
  'FOB',
  '1 set',
  '800 set / Month',
  'China',
  '45 Days',
  'Micron Vending',
  'https://www.micronvending.com/affordable-self-service-dog-wash-stations-for-pet-washing-businesses-in-france.html',
  'https://yunpan.cdn.site.joinf.com/5218418803719614/HE7w2QaciG.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '[]',
  NULL,
  '["Boost your business with our self-service dog washing station","Featuring a smart backend, flexible payments, and advanced hygiene features"]',
  '[["Model NO.","self dog washing machine"],["Delivery","FOB"],["Minimum order quantity","1 set"],["Supply Ability","800 set / Month"],["Country of Origin","China"],["Stock Time","45 Days"]]',
  0,
  1006,
  'Affordable Self-Service Dog Wash Stations for Pet Washing Businesses',
  'Boost your business with our self-service dog washing station. Featuring a smart backend, flexible payments, and advanced hygiene features. Perfect for parks, gas stations, and pet-friendly locations.',
  'https://yunpan.cdn.site.joinf.com/5218418803719614/HE7w2QaciG.png?imageMogr2/thumbnail/500x260/pad/1/color/I0Y2RjZGNg==/quality/85/sharpen/100',
  '2026-05-29T06:35:12.506Z',
  '2026-05-29T06:35:12.506Z'
) ON CONFLICT(category_slug, slug) DO UPDATE SET
  name=excluded.name,
  model_number=excluded.model_number,
  short_description=excluded.short_description,
  overview=excluded.overview,
  delivery=excluded.delivery,
  minimum_order_quantity=excluded.minimum_order_quantity,
  supply_ability=excluded.supply_ability,
  country_of_origin=excluded.country_of_origin,
  stock_time=excluded.stock_time,
  source_site=excluded.source_site,
  source_url=excluded.source_url,
  cover_image_url=excluded.cover_image_url,
  gallery_json=excluded.gallery_json,
  video_url=excluded.video_url,
  key_features_json=excluded.key_features_json,
  specifications_json=excluded.specifications_json,
  seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,
  og_image_url=excluded.og_image_url,
  published_at=excluded.published_at,
  updated_at=excluded.updated_at;
